### ISSUE TITLE
Trémas are fatter than dots on i in bold and heavy 

### ISSUE THREAD

**Issue by kslstn** [indestructible-type/Jost#14]
The tremas on the bold and heavy variants of e.g. ö, ä and ï are larger than the dots on the i. In my opinion, that makes those characters unnecessarily optically heavy. I noticed in other fonts, tremás are sometimes even smaller than the dot on the i.

**Comment by EwonRael** [comment]
I will look into this

**Comment by kslstn** [comment]
Thanks!

**Comment by EwonRael** [comment]
Okay. Version 3.2 should have trémas that are the exact same as the tittles.
