### ISSUE TITLE
lower case 'a' stylistic sets not consistent

### ISSUE THREAD

**Issue by smatth** [indestructible-type/Jost#16]
Using InDesign, I set up a 'waterfall' of text with the different weights which all showed the double story lowercase 'a'. 

When I selected all and changed the Opentype Stylistic Set to Set 1, only the Bold, Heavy and Black weights changed to the single story lowercase 'a'. 

When I looked at the glyphs grid, the double story and single story lowercase 'a ' were in different positions in the grid for Hairline through to Semi weights and showed (Null) for character metadata whereas Bold, Heavy and Black displayed metadata for the single story 'a' characters.

I hope that makes sense.

![renner waterfall](https://user-images.githubusercontent.com/41175003/42669208-9a774ffa-8697-11e8-8e8f-04616b4f3ac1.jpg)

**Comment by EwonRael** [comment]
Okay thanks for pointing this out. I will work on the fix for the next release.

**Comment by EwonRael** [comment]
Okay!

This should be fixed now that version 3.2 has come out!

Thanks for pointing this out.
