### ISSUE TITLE
Polish glyphs lack 2 signs

### ISSUE THREAD

**Issue by zoebull** [indestructible-type/Jost#18]
The latin extended version lacks 2 glyphs: ź  and   ż. It's a great font, but unfortunatelly because of that I cannot use it in my projects :(

**Comment by EwonRael** [comment]
Noted! I will try and include these characters in the next update.

**Comment by EwonRael** [comment]
Okay!

The characters have been added and now Polish should be fully supported!

Thanks for the help!
