### ISSUE TITLE
[Feature Request] Font Variation : Make uppercase AMNW letters tips fit in line

### ISSUE THREAD

**Issue by Ghostium** [indestructible-type/Jost#19]
I really love the style of your font. It is looks very clean.
However, one small thing doesn't look how I wished it were -> the uppercase AM:

Source:
![ts](https://user-images.githubusercontent.com/15706162/43811380-86b47c0c-9abc-11e8-829b-f7379bd42113.PNG)

Badly edited:
![tse](https://user-images.githubusercontent.com/15706162/43811387-8c4bbe6e-9abc-11e8-8165-e033c4138484.PNG)

If you could create a variation or toggleable feature which make sharp glyphs tips fit into the line I would be really grateful. (Including NW, while not used, they are also over the top line).

**Comment by EwonRael** [comment]
Hmmm,

This is an unusual request as the overshoot serves a function, namely it's to compensate for an optical illusion where the pointed letters look uneven if their top is at the same line as other letters'. You will notice that the letter "S" also crosses your red line in both the examples you have provided. This is for a similar reason. 

It's unlikely that I will create a stylistic alternative set that does not do this, as the conditions of that set would be very unclear to me. Do other letters that cross over that imagined line become modified as well? How are the tops of lower-case letters handled? Are other optical illusions accounted for, such as the pointed end of the "Z" that crosses over a similar vertical line?

Besides being theoretically unclear, it's a tremendous amount of work for very little practical use. The  very few situations where I see this as being useful or necessary are ones where manually modifying the letters is the better option, such as in book cover designs.
