### ISSUE TITLE
Renner* still mentioned in a few places

### ISSUE THREAD

**Issue by callahad** [indestructible-type/Jost#21]
This GitHub repository's description:

![image](https://user-images.githubusercontent.com/24193/44345506-79763700-a48b-11e8-91be-ab329b8a0173.png)

The post-purchase page for Jost*:

![jost](https://user-images.githubusercontent.com/24193/44345559-97dc3280-a48b-11e8-93e0-ec38ce43e1f1.png)

**Comment by EwonRael** [comment]
Okay! Thanks for pointing this out!

It's fixed.
