### ISSUE TITLE
Czech glyphs lacks 4 signs

### ISSUE THREAD

**Issue by CatfoodCZ** [indestructible-type/Jost#22]
Hello,
I did notice that there are some glyphs missing: **Ů**, **ů**, **Ť**, **ť**.

![jost](https://user-images.githubusercontent.com/7609251/44460211-7b1b3880-a60c-11e8-9d83-6cda2988c095.jpg)

**Comment by CatfoodCZ** [comment]
Thanks for your reaction.

It would be really great, if you @EwonRael would managed to add those glyphs till Wednesday.
I am willing to pay you some extras for your work through the payment on the font's page.

**Comment by EwonRael** [comment]
Okay! 3.3 includes these characters!
