### ISSUE TITLE
Slant is not optically compensated

### ISSUE THREAD

**Issue by davelab6** [indestructible-type/Jost#23]
Currently the slant axis is just the result of a brute transformation process. 

It should be re-mastered with the result of an "optical compensation" process, or ideally, drawn by hand with such compensations in mind. 

There are scripts around that will slant while doing optical compensation - one is buried in https://github.com/google/roboto/tree/master/scripts/lib/fontbuild , one is built into GlyphsApp (https://glyphsapp.com/tutorials/easy-oblique), I think there are more around on github made for RoboFont... :)

**Comment by EwonRael** [comment]
Yeah this is true! The beans are out!

I used to optically correct them myself, but I have let this habit slide. I will look into these resources, because honestly I don't like the fact that it's not optically corrected.

**Comment by EwonRael** [comment]
Okay I went ahead and used the script in the Roboto source code. 

It worked beautifully, and with some minor touch ups I think has yelded some very lovely italics.

Also exciting is the other transformations in the script. Might come in handy.
