### ISSUE TITLE
[feature request] Support for Polish language?

### ISSUE THREAD

**Issue by mwjoch** [indestructible-type/Jost#30]
This is a beautiful typeface, thank you so much Owen for creating it and making it available for free. I am wondering if there is any chance of having Polish characters in the future?

**Comment by EwonRael** [comment]
Hey!
I'm confused about what characters I need to include in order to support Polish? I already have ą, ć, ę, ł, ń, ó, ś, ź, ż. What am I missing here?

Sorry that I'm unfamiliar with the Polish language.

**Comment by mwjoch** [comment]
Thanks for your reply and apologies for getting back to you late. I didn't realise there were already Polish characters, my bad! Anyway, this is absolutely excellent and thank you again for this beautiful typeface.

**Comment by EwonRael** [comment]
Thanks!
