### ISSUE TITLE
[feature request] Support for Slovak language?

### ISSUE THREAD

**Issue by hdche** [indestructible-type/Jost#31]
Hello there, first of all Jost is awesome type! And I have another feature request. Please do not forget about Slovak language :) 

Try words as: Topoľčany, kôň, šteká, žriebä, vôkol, čaša, dopĺňanie mäkčeňov a dĺžňov, tŕň, vôkol tŕnia kráčalo tridsať koní, ílovitá pôda, bábätko.

Much love.

**Comment by EwonRael** [comment]
...I'm confused.

Don't I already support all the characters in your "try words" example? I just pasted that into the "Test Jost* Out" section [of the website](https://indestructibletype.com/Jost.html) and it works.

Am I missing something here?
