### ISSUE TITLE
Fontmake will create an empty ttf folder

### ISSUE THREAD

**Issue by ghost** [indestructible-type/Jost#32]
Hi,

once I run ```fontmake -o variable -m jost.designspace``` it creates an empty folder called variable_ttf in the directory. Am I missing something? I already purchased the font but I want to make some adjustments to it.
Changing letters in glyphs.app will create an unusable variable font ttf file. I guess the variable font export function is still in its beta.

**Comment by EwonRael** [comment]
To be perfectly honest with you it seems like every time they update fontmake they come up with some new way to make it not work quite right for variable fonts. 

It's a real imperfect application and I have to re learn how to configure it every time I want to update the variable font.

I don't have any answers for you other than I'm not surprised. I tend to mess around with it and brute-force my way to something that works.

When I release the next version of Jost* I will revisit the variable font too and if I run into any issues (and more importantly solutions) I will update the Jost* source code to reflect this.

Good luck!

**Comment by irrg** [comment]
I almost created a new issue because of the title of this one—it might be worth editing the title and having it read 'fontmake fails compiling the variable font' just so people can more easily find this answer.

**Comment by EwonRael** [comment]
I have redone the way the font generates the variable version. Try running the build.sh script in the latest version and see if you still run into issues!
