### ISSUE TITLE
Hairline Italic has Jost* 200 Hairline Italic in Style Group

### ISSUE THREAD

**Issue by kenmcd** [indestructible-type/Jost#33]
The Hairline Italic file has **Jost 200 Hairline Italic** in Style Group.  
This causes it to be displayed like that in the LibreOffice font list.  
It should read **Jost 100 Hairline Italic**  (100 not 200).  

I see that all of the italic fonts have a separate style group.
The Regular and Italic of each weight should have the same style group.
Modern applications will not use these name fields, just older apps like LibreOffice.

**Comment by EwonRael** [comment]
fixed
