### ISSUE TITLE
No style links

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Jost#36]
![winword_2019-01-30_14-51-24](https://user-images.githubusercontent.com/47187428/51997776-89645f00-249e-11e9-8b56-8c82efc509fe.png)
Rather than seeing the fonts like this on the font menu, I would like to only see the roman versions, and to see the italics only when selecting the “italic” style option. This worked in an older version:
![winword_2019-01-30_14-53-01](https://user-images.githubusercontent.com/47187428/51997876-bfa1de80-249e-11e9-9947-a64923721e16.png)
As you can see, the Bold is also proprely style linked here, and thus not on the list – I may access it by selecting the Regular and using the bold style.

**Comment by EwonRael** [comment]
I hope you never stop posting issue reports!

You are right. I will fix this.

**Comment by EwonRael** [comment]
I think that I fixed this. Let me know if you have any trouble.
