### ISSUE TITLE
Weird printing issues when using Jost in Word

### ISSUE THREAD

**Issue by ChriKn** [indestructible-type/Jost#40]
I love this font and want to use it in every document I make.
Sadly it seems to not be optimised for use in Microsoft Office, as I try to use only the 300 font which I than turn Bold when needed (like any other font).
The printer gives me a skeleton of the font itself (while still looking fine on screen)

Is there a way to have a font file for offline work, where it just works like Arial or NTR ?

I am really uneducated with everything regarding fonts, so please forgive this probably dumb question if I didn't catch something or got the wrong version.

Thanks for this great work.

**Comment by EwonRael** [comment]
thanks for the love and support.

I honestly don't know what would be causing this. Can you try downloading and installing the latest version and then providing a screenshot?

It may be an issue with the font but unless I can learn more about it or recreate the issue on a computer I have access to I wouldn't be able to troubleshoot.

Sorry for the late reply. For some reason I missed most of the issue reports on this font and am only just getting to them.
