### ISSUE TITLE
Is it possible to use Jost as one font in word ?

### ISSUE THREAD

**Issue by ChriKn** [indestructible-type/Jost#41]
I try to use this great font for my contracts (much easier to read for many people, they ask me about it all the time).
Sadly using it in word is a bit painful, as I can't simply use "bold / italic" without ruining the typeface.

Would it be possible to make the font behave like many others where Word only sees the "regular be it 300 or 400" one and applies the "bold" and "italic" nomenclature accordingly without having to switch the font each time ?

Or am I just missing something ?

**Comment by EwonRael** [comment]
Hello!

This is indeed an issue, and was in fact reported on [here](https://github.com/indestructible-type/Jost/issues/36).

It is possible to fix this, and it is my intention to fix this. Unfortunately I have been exceedingly busy recently and have not been able to work on fonts.

I will fix this as soon as I am able!

**Comment by ChriKn** [comment]
Thanks for the quick reply ! Eager to try this when it happens

**Comment by EwonRael** [comment]
This should be fixed. Changes available on Github. Should be online soon.
