### ISSUE TITLE
Document alternate character sets

### ISSUE THREAD

**Issue by gmosx** [indestructible-type/Jost#43]
First of all, *thank you* for this amazing font!

The Web site mentions that Jost supports alternate characters (e.g. single-story 'a', tabular numbers, etc.). It would be great if these options were documented in the `README.md` file with specific details about how to enable them in CSS, etc.

**Comment by EwonRael** [comment]
thanks for the support!

I will look into this. Sorry I didn't see this the first time.

**Comment by johncrim** [comment]
I agree, @gmosx - Jost is a phenomenal font. Thank you @EwonRael  - money coming to you once our startup raises money, if we use it.

I've found that tabular numbers work as expected with Jost - just use:
```css
span.numbers {
  font-variant-numeric: tabular-nums;
}
```

I haven't yet figured out how to make the upper-cased 'J' use a standard height (eg matching the other upper-cased character heights) in CSS. I'll post here if I'm able to figure that out. For our use, these are the 2 must-haves.

**Comment by EwonRael** [comment]
Right now there isn't a upper-case "J" like that. You could request it to be added, but that should be a new issue
