### ISSUE TITLE
Do you take sugestion for lettershape improvement?

### ISSUE THREAD

**Issue by synthview** [indestructible-type/Jost#47]
Hello,
I wanted to ask if you accept suggestions for improve some glyph lettershape?
I am a type designer and use Glyphs app, I could redraw some shapes based on your master files.
All best,
Jan

**Comment by EwonRael** [comment]
Yeah sure thing!

If you could send them in the form of UFO files or make a pull request that would be great!

Obviously I would want to see the letters before incorporating them into the font.

**Comment by synthview** [comment]
OK thanks. I see you have an UFO for each weight. May I modify just the extremes and you'll manage to interpolate them? Usually I work with a multimaster file, but I know in Glyhps I can edit also UFOs.

**Comment by EwonRael** [comment]
UFO for extremes _and_ book weight would be best. Just extremes cause weirdness in the middle area.

**Comment by synthview** [comment]
I have some issues with the ufos as opentype features are not recognized and I see no kerning neither :(
However, I can send you via email a file with just the changed glyphs. In brief, it would be letters: a s S W.
for a and s, I had started on "medium", but I'm attaching a screenshot here to let you see what I have in mind. On the right my modified version. 
What do you think? :)
![Screenshot 2019-12-07 at 11 49 38](https://user-images.githubusercontent.com/1451689/70373326-4659f000-18e8-11ea-9180-a50d21338622.png)

**Comment by EwonRael** [comment]
Changes look good. Just send me the glyphs and I'll figure it out. 👍👍

**Comment by EwonRael** [comment]
Also- medium is less important because I start by interpolating book and extremes, not medium

**Comment by synthview** [comment]
Yes, I had drawn them before reading you message about book. I'll redraw the 3 weights and sned them to you. How can I send you the files? I don't know how to push them on github…

**Comment by EwonRael** [comment]
indestructibletype@gmail.com

**Comment by synthview** [comment]
Hi! did you receive my email?

**Comment by EwonRael** [comment]
Yes! Sorry thanks for the reminder. I got the email but it will take a while for me to figure out how I want to integrate this into the font. 

Should have responded though.

**Comment by synthview** [comment]
No problem! It was just to be sure my mail did not went into spam.

**Comment by EwonRael** [comment]
Hello!

These changes have been made to the font.

The italics are not automatically generated and you did not provide matching italics. In some cases I drew new italics to match the changes you've suggested. The book "S" is an example of this. In other cases I left the italic version as is.

Because the variable version of the font goes to 200%, I made the standard italics by interpolating the VF version with the romans. If you were looking to draw matching italics it would only be helpful to me if they were twice the angle the finished italics are. The VF ufo files are in the "sources" file.

I'm going to leave this issue open even though I've incorporated the changes in the off chance that you wanted to draw italics.

No pressure either way.

**Comment by synthview** [comment]
Hello ! You're right, I'll draw italics as I'll be back from vacation. About your UFO files, I can't see kerning information. Do you see it on your side? If not, is there a way to provide UFO with wmbedded kerning data please?

**Comment by EwonRael** [comment]
hmm. The UFO files should have kerning data?

I'm going to close this issue. If you want to send me italic versions of the glyphs you're fixing up I'll incorporate them as I have the non italics, otherwise I have made italic versions that are hopefully agreeable.

**Comment by synthview** [comment]
Chapter "File Structure"
http://unifiedfontobject.org/versions/ufo3/
I work on Mac, so I see an unique file package and my font editor loads everything, so it's quite easy to work with a pre-existing file. 
I'm sorry I had no time to work on your italics and then I have forgotten.  I'll try to do it in the very next days.
All best
