### ISSUE TITLE
[feature request] Rouble Symbol

### ISSUE THREAD

**Issue by shaltai** [indestructible-type/Jost#49]
I will be very appreciate if you add symbol for Russian currency — ₽. 
`U+20BD ₽ RUBLE SIGN symbol for Unicode version 7, (HTML &#8381;)`

Thank you in advance! :-)

**Comment by EwonRael** [comment]
Will do

**Comment by shaltai** [comment]
🥺

**Comment by EwonRael** [comment]
should be taken care of now!
