### ISSUE TITLE
Incorrect otf font names in 3.5

### ISSUE THREAD

**Issue by Amphiboly** [indestructible-type/Jost#50]
The 800 weight otf fonts are hevy and hevyitalic (but should be Heavy and HeavyItalic).

**Comment by EwonRael** [comment]
I can't reproduce this issue. Can you give me more context?

**Comment by Amphiboly** [comment]
Sure. Here is a screen shot from https://github.com/indestructible-type/Jost/tree/master/fonts/otf:
![Jost_otf_names](https://user-images.githubusercontent.com/10307457/72737932-85799300-3b6e-11ea-8337-a3dd0b4d981d.png)
Note the spelling of the 800-weight font names. The ttf font names are spelled correctly.

**Comment by EwonRael** [comment]
oh yes of course. I am relieve to learn that this is not a metadata issue, so it is an easy fix!

Should be good now!

**Comment by levibe** [comment]
Just a heads up that the fonts in `/fonts/otf` and `/fonts/ttf` are still named Hevy and HevyItalic even though this issue is marked closed.
