### ISSUE TITLE
Website says version 3.4, but it's 3.5

### ISSUE THREAD

**Issue by legion80** [indestructible-type/Jost#51]
Last paragraph of https://indestructibletype.com/Jost.html

> ALWAYS IMPROVING
>     Jost* is now at version 3.4, meaning this font has been worked and reworked since its inception. Many of the changes and improvements have come directly from the community. If there are ways that you think Jost* can be improved, reach out and maybe Jost* 3.5 will include that feature or fix.

Should be 3.5, 3.6.

**Comment by EwonRael** [comment]
fixed
