### ISSUE TITLE
α letter

### ISSUE THREAD

**Issue by Nic787** [indestructible-type/Jost#58]
Hi,

Since this font is based on Futura, would it be possible to have an alternate a (α) and a lowercase U without the small leg/tail u?

Thank you :)
--

Nic

**Comment by EwonRael** [comment]
This font already has an alternative a.

I feel weird about adding the "u". I don't know why I would do that other then wanting a font that is visually indistinguishable from Futura, but why not use Futura in that case? 

I'm open to persuasion though.

**Comment by Nic787** [comment]
Hi,

My bad I didn’t read correctly about the alternate a on the font website. How do I use it on my website?

You are also right about the u.

Thank you

**Comment by EwonRael** [comment]
Hey.

Honestly I have no idea how to use alternative letters in case

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates

This article seems like a good starting place.

From a graphic design I really don't understand the "u" thing. If the font is being used to write paragraphs and stuff then a difference that subtle is not meaningful. If the font is being used for a logo or something where that kind of thing actually makes a difference then modifying the shape of the "u" by hand is a better solution then changing the font.
