### ISSUE TITLE
Review GF spec

### ISSUE THREAD

**Issue by davelab6** [indestructible-type/Jost#63]
Please review https://github.com/googlefonts/gf-docs/tree/master/Spec as this provides clearer docs about what GF requires for final publication

**Comment by EwonRael** [comment]
I will run through this and do my best to get Jost* aligned with what's outlined out here.

**Comment by EwonRael** [comment]
Hey! I looked this over and as far as I can tell everything conforms to what's outlined in the spec sheet. Let me know if I'm overlooking something?
