### ISSUE TITLE
Single story lowercase "a" standart

### ISSUE THREAD

**Issue by europanew** [indestructible-type/Jost#66]
The Jost font i great! Thanks!

1 request:

PLEASE make the 'a' single story.. it looks better.

Regards

**Comment by EwonRael** [comment]
Hi!

This font already has a single story a as a substitution glyph. I'm not going to make it default but it's there as an option.

Thanks for the support!

**Comment by EwonRael** [comment]
Hi!

This font already has a single story a as a substitution glyph. I'm not going to make it default but it's there as an option.

Thanks for the support!
