### ISSUE TITLE
Curved j and t alternates?

### ISSUE THREAD

**Issue by Elendil03** [indestructible-type/Jost#67]
Hello there! I'm a big fan of the Jost* typeface (it seems to be the best Futura recreation available and one of the best free Geometric Sans). Though when in use, it could be easily mistaken for Futura itself or another design based on it, which is not always favorable. This is why I would very much appreciate if you considered adding a stylistic set that omits Futura's most iconic characteristics, namely the straight descenders of the j and t glyphs, thus making it a bit more similar to Avenir.
I can't estimate how much effort this would mean as regards adjusting diacritics placement etc, but it would certainly make Jost* a lot more versatile.

**Comment by EwonRael** [comment]
Hi!

Thanks for the feedback. I am a little confused about what you mean with the curved j? Jost* already has a curved upper and lowercase j, unless I'm misunderstanding what you mean?

Depending on how things go I could see myself implementing a curved lowercase t. I would point out that the t is different from Futura, in that the cross-stroke is centred. Futura's t's cross-stroke is off to the right quite a bit.

I would also point you to the lovely [Spartan](https://fonts.google.com/specimen/Spartan), which Mirko also contributed to. It's a bit more in the Avenir territory with it's curved t and such. The [MB version](https://www.fontsquirrel.com/fonts/spartan-mb) has a double story a as an alternative glyph if the single story a bothers you.

**Comment by Elendil03** [comment]
Right, thank you very much for the quick answer. I admittedly didn't check the j glyph before asking, the t shape was my main concern. I have used Jost* for two personal projects, but then thought it was too similar to Futura in order to really stand out (there's a lot of Futura around in my area so it's usually seen as a bit lackluster, that's why I've left it unused during the past few weeks).
I thought about utilizing Spartan instead, but the lack of Obliques deterred me.

**Comment by Elendil03** [comment]
So let's hope things go well.,,
