### ISSUE TITLE
cramped characters in bold font on android

### ISSUE THREAD

**Issue by Infi-Knight** [indestructible-type/Jost#68]
Hi there. Thanks for creating this amazing font. As you can see in the image,  the characters 'c' seems vertically cramped on my android device when rendered in bold. Is this the expected behavior? I am using the variable fonts generated using build scripts.
[Imgur](https://i.imgur.com/F00s3pl.jpg)

**Comment by EwonRael** [comment]
Hi-
Those are the automatic bold characters that are created if the proper bold version of the font is not installed. I assume that Android doesn't support variable font technology yet. Try installing the static versions and see what happens.

**Comment by Infi-Knight** [comment]
I forgot to include the `font-weight` descriptor in `@font-face` rule resulting in the issue. It's resolved now. Closing the issue
