### ISSUE TITLE
the "a" :D

### ISSUE THREAD

**Issue by Gontora** [indestructible-type/Jost#77]
Hi :)

First! 
Amazin work! THX for all the time and work! Thx all!
My question is and maybe not only mine.
Is it possible to add the original a from futura as an optionen? Where u can decide which "a" u can use? the normal one or the round one like futuras? Would be amazing!

greetings

G

**Comment by Gontora** [comment]
Hi again. 
I found it its in Indesign under Opentype :D That's EPIC!
So there is an Alternate "a"! YAY!!!

And now the main question 🍡 
How can i set this up for the webfont?

THX!

greetings

G

**Comment by Gontora** [comment]
I think i found it lets test it out 👍 

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates

**Comment by Gontora** [comment]
Dang...its only for firefox...
Hm..
please... help!

**Comment by Gontora** [comment]
I found this but i cant find the right code for the one maybe someone can help me out?

https://css-tricks.com/almanac/properties/f/font-feature-settings/

thx!

greetings

G

**Comment by Gontora** [comment]
https://helpx.adobe.com/de/fonts/user-guide.html/de/fonts/using/open-type-syntax.ug.html#salt

it should be this but wount work :(

.class {
  -moz-font-feature-settings: "ss01";
  -webkit-font-feature-settings: "ss01";
  font-feature-settings: "ss01";
}

**Comment by EwonRael** [comment]
I tested that CSS out myself and it's working fine on both firefox and chrome. My guess is that your syntax is off and it's not applying what you've written to your text. 

Can you include all of your CSS so we can have some context?

**Comment by Gontora** [comment]
> I tested that CSS out myself and it's working fine on both firefox and chrome. My guess is that your syntax is off and it's not applying what you've written to your text.
> 
> Can you include all of your CSS so we can have some context?

Well i think the problem was that i had google fonts on it. 
I downloaded the one from here and generated them with fontsquirels font-generator with alternate-options on expert mode and uploaded them with @font-face

btw will it work somehow with google-font-linking?

oh and maybe there is a possibility to have an alternate "U" too? like on futura? would be amazing too 👍 

thx btw for the answer and all the work! great stuff <3<3<3

greetings

G

**Comment by Gontora** [comment]
I have a problem.
For example, when I wanted to generate the book variant he didn't want to generate it for me at Font-squirel.
This is what i did: [link](https://1drv.ms/u/s!As_asC_vOAP2ivMoeXEwCNW-FVf13Q?e=UxD3vG)
On some Styles it works on some not.
How can i fix it? 

greetings

G

**Comment by Gontora** [comment]
> I have a problem.
> For example, when I generate the book variant it didn't want to generate it for me at Font-squirel.
> This is what i did: [link](https://1drv.ms/u/s!As_asC_vOAP2ivMoeXEwCNW-FVf13Q?e=UxD3vG)
> On some Styles it works on some not.
> Iv tried turn off open type futures and open type Flattering or one off one on mixing still wount work.
> It works without but then the a is normal.
> How can i fix it?
> 
> greetings
> 
> G

oh ok i put the code inside the css:

.class {
-moz-font-feature-settings: "ss01";
-webkit-font-feature-settings: "ss01";
font-feature-settings: "ss01";
}

and it works i dont need add them i see.

greetings

**Comment by Gontora** [comment]
Ok whats working ist 400 and 500 but what about the rest? is there no alt "a"?

greetings

G

**Comment by Gontora** [comment]
here I made a test page: https://zumquadrat.org/font-test/
I dont get it :/

**Comment by EwonRael** [comment]
Hi hello,

Thanks for including the test page. This is very helpful to me.

On that test page the versions that aren't displaying the alt "a" correctly don't have the alt "a"s in the font file, which means something is wrong with the font itself.

This either means when you're converting to woff something is going amiss, or something is wrong with the source files.

I have updated the indestructible type* website with the latest builds of Jost*. I have double checked to make sure the alternative "a" is there and correctly built. [Here is a link](indestructibletype.com/Jost/Jost.zip).

Try building from that and if the problem persists then it's likely something on your end.

Thanks for your help and feedback.

**Comment by Gontora** [comment]
> Hi hello,
> 
> Thanks for including the test page. This is very helpful to me.
> 
> On that test page the versions that aren't displaying the alt "a" correctly don't have the alt "a"s in the font file, which means something is wrong with the font itself.
> 
> This either means when you're converting to woff something is going amiss, or something is wrong with the source files.
> 
> I have updated the indestructible type* website with the latest builds of Jost*. I have double checked to make sure the alternative "a" is there and correctly built. [Here is a link](indestructibletype.com/Jost/Jost.zip).
> 
> Try building from that and if the problem persists then it's likely something on your end.
> 
> Thanks for your help and feedback.

Thx alot but the link is missing :( it says not found. maybe there is another link?

thx

greetings

Gonto

**Comment by EwonRael** [comment]
https://indestructibletype.com/Jost/Jost.zip

**Comment by EwonRael** [comment]
Sorry, I missed typed the link the first time

**Comment by Gontora** [comment]
btw i cant create all fonts on fontsquirel i dont know why but he wount create some of the font-style with all the types lik woff, svg and so on. Is it possible to get all the font-style from somewhere else? i need all of them: woff, woff2, svg, eot, ttf. Its kinda strange and i dont know why it wount let me create them on fontsquirell 👍 

thx alot

greetings

G

**Comment by Gontora** [comment]
i made it. here are the settings i made:
[Create Your Own @font-face Kits _ Font Squirrel.pdf](https://github.com/indestructible-type/Jost/files/5252064/Create.Your.Own.%40font-face.Kits._.Font.Squirrel.pdf)


here the site: https://zumquadrat.org/font-test/
