### ISSUE TITLE
right sidebearing appears to be off with right and left single quotes

### ISSUE THREAD

**Issue by davebellows** [indestructible-type/Jost#8]
On both my website and in pdfs I create of my documents, whenever I have a right single quote being used as an apostrophe (eg: "John's"), it looks like there's a bigger gap between the quote and the "s" that follows (or any other letter that follows). Following is a screenshot of a document with the word "let's" with the extra spacing after the apostrophe.

![sidebearing](https://user-images.githubusercontent.com/5007215/41388650-cd2c2afa-6f41-11e8-86cf-96d038c730d5.png)

**Comment by EwonRael** [comment]
Hey!

It looks like the kerning information for the letters "s" and "d" when on the left side got deleted at some point down the line. This means that there's too much space for those letters, but the kerning should look decant for other letters. This is a fairly involved fix, so I'm going to "patch" this for the book and bold weights right now, and then in a future update more throughly address this.

**Comment by EwonRael** [comment]
yeah okay so as of right now this should be fixed for the book and bold weights. It's kind of a hack fix, and it's hasn't been applied to any other weights.

I will make sure to address this on a deeper level in the next update, but that will be a while.

**Comment by davebellows** [comment]
Thank you! I use book anyway so this is perfect.

**Comment by EwonRael** [comment]
Okay the latest version fixes this on a deeper level and for all weights.
