### ISSUE TITLE
Letter "ų" ogonek placement

### ISSUE THREAD

**Issue by MariusPaulikas** [indestructible-type/Jost#81]
Hello. I'm currently working with a lithuanian team on a new web platform, and we've chosen Jost as our main font; However, right after making the choice, we noticed a problem with lithuanian character "ų" (the ogonek is misplaced). I tried to fix the letter myself but ran into some issues (I've no experience in font editing). When is this likely to be fixed?

Someone (donatasben) has already pointed out this problem earlier:
![82912408-c0a12e00-9f75-11ea-8d51-64faa579c277](https://user-images.githubusercontent.com/75433281/101029129-a2019c80-3581-11eb-8312-61cf49d07924.jpg)

**Comment by EwonRael** [comment]
Hey!

Let me know if the new one looks good I tried to fix it!

**Comment by MariusPaulikas** [comment]
Oh wow, that was blazing fast! Looks good. Thank you so much man, you saved us here!

**Comment by alirenaa** [comment]
Hey! It's started again :(
