### ISSUE TITLE
displaying strange when characters have a stroke on them

### ISSUE THREAD

**Issue by sideseven** [indestructible-type/Jost#88]
I've been trying to add a stroke to the font in illustrator and it's displaying some of the characters really strangely. 
<img width="600" alt="Screenshot 2021-08-23 at 14 35 04" src="https://user-images.githubusercontent.com/89398275/130456522-ba2ae2a7-11f3-4fcb-b2f7-5d131614a8ff.png">

**Comment by neins** [comment]
There is a newer version without this bug on their [site](https://indestructibletype.com/Jost)

**Comment by sideseven** [comment]
Ah awesome thank you!
