### ISSUE TITLE
Text outline shows original lines

### ISSUE THREAD

**Issue by pixieLinxie** [indestructible-type/Jost#90]
When outlining text, it doesn't create a clean outline (see attached)
![image](https://user-images.githubusercontent.com/72343232/134204657-ca7201ae-fcb8-4b2c-a9d8-345a6d99402b.png)

**Comment by EwonRael** [comment]
Unfortunately the letters have to be constructed this way to work as variable fonts

**Comment by uxrjames** [comment]
Hi Ewon,
Thanks for creating this wonderful font. I have become quite attached to it but this outline issue is getting me down!

I have the same problem as above, even when I use the static versions. Is there a way to fix this? 

I don't necessarily need a variable font, but I do need one that I can apply stroke with good effect using CSS.

Many thanks!
